project:
  type: book

book:
  title: "Rによる気象データサイエンス"
  author: "榎本剛"
  date: "2023/6/4"
  chapters:
    - index.qmd
    - intro.qmd
    - regression.qmd
    - eof.qmd
    - function.qmd
    - sst.qmd
    - map.qmd
    - reanalysis.qmd
    - frontogenesis.qmd
    - poisson1d.qmd
    - l96.qmd
    - torch.qmd
    - foreign.qmd
    - quarto.qmd
    - references.qmd
  output-file: "rmetds"
  downloads: pdf

bibliography: references.bib
csl: american-meteorological-society.csl

toc: true
format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    papersize: a4paper
    keep-tex: true
    documentclass: bxjsbook
    classoption:
      - pandoc
      - ja=standard
      - jafont=haranoaji
pdf-engine: lualatex


